In [1]:
import pandas as pd

meeting_note_csv_path = r"C:\workspace\python\audio\싼기타_비싼기타_final.csv"
df_rttm = pd.read_csv(meeting_note_csv_path, sep='|')

display(df_rttm)

,start,end,speaker_id,duration,text
0,0.976,30.195,SPEAKER_01,29.219,지금부터 저랑 역할극을 합시다.\n역할극을 스탠드인 코미디 스타일로 할 건데\n토론...
1,32.419,41.638,SPEAKER_00,9.219,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...
2,41.638,42.453,SPEAKER_01,0.815,NaN
3,41.655,42.725,SPEAKER_00,1.070,NaN
4,42.674,44.032,SPEAKER_01,1.358,"네, 됐어요. 시작하시죠.\n"
5,45.798,67.105,SPEAKER_00,21.307,좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.\n초보자일 때는 ...
6,67.224,82.793,SPEAKER_01,15.569,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\..."
7,84.643,102.572,SPEAKER_00,17.929,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...
8,103.489,117.530,SPEAKER_01,14.041,싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요...
9,119.737,138.667,SPEAKER_00,18.930,하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 ...
10,139.346,168.956,SPEAKER_01,29.610,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...
11,170.925,192.318,SPEAKER_00,21.393,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기...
12,192.317,193.692,SPEAKER_01,1.375,NaN
13,192.776,193.523,SPEAKER_00,0.747,NaN
14,193.812,216.579,SPEAKER_01,22.767,쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에...
15,218.565,237.767,SPEAKER_00,19.202,하하 비싼 기타가\n일종의 동기부여가 된다는\n말씀이시군요. 하지만 반대로 비싼 기...
16,238.107,238.667,SPEAKER_01,0.560,NaN
17,238.175,239.346,SPEAKER_00,1.171,결국은 본인이 선택한...\n
18,239.856,240.654,SPEAKER_01,0.798,NaN
19,240.314,241.010,SPEAKER_00,0.696,NaN
20,241.044,251.316,SPEAKER_01,10.272,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...
21,253.659,271.553,SPEAKER_00,17.894,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...
22,272.148,304.541,SPEAKER_01,32.393,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와\n비싼 기...
23,306.986,326.035,SPEAKER_00,19.049,하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타...
24,326.358,335.459,SPEAKER_01,9.101,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...
25,337.547,355.934,SPEAKER_00,18.387,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...
26,356.256,363.981,SPEAKER_01,7.725,아 맞아요.\n그 지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n
27,365.968,381.435,SPEAKER_00,15.467,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게..."
28,382.165,383.727,SPEAKER_01,1.562,어? 지금 도망가시는 건가요?\n
29,385.713,397.174,SPEAKER_00,11.461,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...
30,397.615,399.092,SPEAKER_01,1.477,NaN
31,401.435,406.596,SPEAKER_00,5.161,"아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n"
32,407.326,408.345,SPEAKER_01,1.019,화난 것 같은데?\n
33,410.093,417.445,SPEAKER_00,7.352,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n"
34,417.750,421.230,SPEAKER_01,3.480,계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 ...
35,423.642,429.346,SPEAKER_00,5.704,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n

In [2]:
# 이름 넣기
name_dict = {
    "SPEAKER_00": "AI",
    "SPEAKER_01": "이성용",
}

df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict[x])

display(df_rttm)

,start,end,speaker_id,duration,text,name
0,0.976,30.195,SPEAKER_01,29.219,지금부터 저랑 역할극을 합시다.\n역할극을 스탠드인 코미디 스타일로 할 건데\n토론...,이성용
1,32.419,41.638,SPEAKER_00,9.219,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...,AI
2,41.638,42.453,SPEAKER_01,0.815,NaN,이성용
3,41.655,42.725,SPEAKER_00,1.070,NaN,AI
4,42.674,44.032,SPEAKER_01,1.358,"네, 됐어요. 시작하시죠.\n",이성용
5,45.798,67.105,SPEAKER_00,21.307,좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.\n초보자일 때는 ...,AI
6,67.224,82.793,SPEAKER_01,15.569,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\...",이성용
7,84.643,102.572,SPEAKER_00,17.929,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...,AI
8,103.489,117.530,SPEAKER_01,14.041,싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요...,이성용
9,119.737,138.667,SPEAKER_00,18.930,하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 ...,AI
10,139.346,168.956,SPEAKER_01,29.610,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...,이성용
11,170.925,192.318,SPEAKER_00,21.393,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기...,AI
12,192.317,193.692,SPEAKER_01,1.375,NaN,이성용
13,192.776,193.523,SPEAKER_00,0.747,NaN,AI
14,193.812,216.579,SPEAKER_01,22.767,쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에...,이성용
15,218.565,237.767,SPEAKER_00,19.202,하하 비싼 기타가\n일종의 동기부여가 된다는\n말씀이시군요. 하지만 반대로 비싼 기...,AI
16,238.107,238.667,SPEAKER_01,0.560,NaN,이성용
17,238.175,239.346,SPEAKER_00,1.171,결국은 본인이 선택한...\n,AI
18,239.856,240.654,SPEAKER_01,0.798,NaN,이성용
19,240.314,241.010,SPEAKER_00,0.696,NaN,AI
20,241.044,251.316,SPEAKER_01,10.272,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...,이성용
21,253.659,271.553,SPEAKER_00,17.894,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...,AI
22,272.148,304.541,SPEAKER_01,32.393,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와\n비싼 기...,이성용
23,306.986,326.035,SPEAKER_00,19.049,하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타...,AI
24,326.358,335.459,SPEAKER_01,9.101,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...,이성용
25,337.547,355.934,SPEAKER_00,18.387,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...,AI
26,356.256,363.981,SPEAKER_01,7.725,아 맞아요.\n그 지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n,이성용
27,365.968,381.435,SPEAKER_00,15.467,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게...",AI
28,382.165,383.727,SPEAKER_01,1.562,어? 지금 도망가시는 건가요?\n,이성용
29,385.713,397.174,SPEAKER_00,11.461,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...,AI
30,397.615,399.092,SPEAKER_01,1.477,NaN,이성용
31,401.435,406.596,SPEAKER_00,5.161,"아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n",AI
32,407.326,408.345,SPEAKER_01,1.019,화난 것 같은데?\n,이성용
33,410.093,417.445,SPEAKER_00,7.352,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n",AI
34,417.750,421.230,SPEAKER_01,3.480,계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 ...,이성용
35,423.642,429.346,SPEAKER_00,5.704,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n,AI

In [3]:
meeting_note_txt = df_rttm[['start', 'end', 'name', 'text']].to_json(orient='records', force_ascii=False)
print(meeting_note_txt)

[{"start":0.976,"end":30.195,"name":"이성용","text":"지금부터 저랑 역할극을 합시다.\n역할극을 스탠드인 코미디 스타일로 할 건데\n토론을 하면서 자연스럽게 대화하는 형식으로 하면서\n코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요.\n자연스럽게.\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n어, 두 중에 어떤 역할 맡으실래요?\n"},{"start":32.419,"end":41.638,"name":"AI","text":"좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠? 네 맞아요. 준비 되셨나요?\n"},{"start":41.638,"end":42.453,"name":"이성용","text":null},{"start":41.655,"end":42.725,"name":"AI","text":null},{"start":42.674,"end":44.032,"name":"이성용","text":"네, 됐어요. 시작하시죠.\n"},{"start":45.798,"end":67.105,"name":"AI","text":"좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.\n초보자일 때는 실수도 많고 기타에 익숙해지는 과정이 필요하니까\n비싼 기타보다는 부담�없이 연습할 수 있는 싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n"},{"start":67.224,"end":82.793,"name":"이성용","text":"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타 사고 쌍기타 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n"},{"start":84.643,"end":102.572,"name":"AI","text":"그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 쌍기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요.\n그리고 기타 연주에 익숙해지면 그때 비교할 수 있는 게 더 좋다고 생각해요.\n그리고 기타 현지에 익숙해지면\n그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데\n"},{"start":103.489,"end":117.53,"name":"이성용","text":"싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데 기타를 싼 거 산다고 달라지나요?\n"},{"start":119.737,"end":138.667,"name":"AI","text":"하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에 부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요.\n그리고 싼 기타도 요즘은\n통질이 꽤 좋아서 연습용으로\n"},{"start":139.346,"end":168.956,"name":"이성용","text":"충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타로 사서 하면 되는 거 아니에요?\n그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면\n자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.\n"},{"start":170.925,"end":192.318,"name":"AI","text":"하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기타를 기타의 흥미가 떨어지거나\n생각보다 연습시간이 적을 때\n아까울 수도 있습니다.\n이 기타의 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n"},{"start":192.317,"end":193.692,"name":"이성용","text":null},{"start":192.776,"end":193.523,"name":"AI","text":null},{"start":193.812,"end":216.579,"name":"이성용","text":"쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에요. 왜냐하면 그 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n측면에서도 비싼 기타가 훨씬 도움이 된다고\n생각을 합니다.\n"},{"start":218.565,"end":237.767,"name":"AI","text":"하하 비싼 기타가\n일종의 동기부여가 된다는\n말씀이시군요. 하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.\n그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n"},{"start":238.107,"end":238.667,"name":"이성용","text":null},{"start":238.175,"end":239.346,"name":"AI","text":"결국은 본인이 선택한...\n"},{"start":239.856,"end":240.654,"name":"이성용","text":null},{"start":240.314,"end":241.01,"name":"AI","text":null},{"start":241.044,"end":251.316,"name":"이성용","text":"근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n"},{"start":253.659,"end":271.553,"name":"AI","text":"맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게 선택하는 게 최선이겠네요.\n"},{"start":272.148,"end":304.541,"name":"이성용","text":"아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와\n비싼 기타를 치더라도 이게 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로 비싼 기타를 치던 사람이\n싼 기타를 치면은\n아 이게 이렇게 싸구려구나 라는 걸\n금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 그 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작하는 게 좋죠.\n"},{"start":306.986,"end":326.035,"name":"AI","text":"하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히\n연습하는 게 제일 중요하겠죠?\n"},{"start":326.358,"end":335.459,"name":"이성용","text":"맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n"},{"start":337.547,"end":355.934,"name":"AI","text":"그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n"},{"start":356.256,"end":363.981,"name":"이성용","text":"아 맞아요.\n그 지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n"},{"start":365.968,"end":381.435,"name":"AI","text":"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게 이야기 나누는 게 더 중요한 것 같아요\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n"},{"start":382.165,"end":383.727,"name":"이성용","text":"어? 지금 도망가시는 건가요?\n"},{"start":385.713,"end":397.174,"name":"AI","text":"아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 혹시 화나셨나요?\n"},{"start":397.615,"end":399.092,"name":"이성용","text":null},{"start":401.435,"end":406.596,"name":"AI","text":"아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n"},{"start":407.326,"end":408.345,"name":"이성용","text":"화난 것 같은데?\n"},{"start":410.093,"end":417.445,"name":"AI","text":"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n"},{"start":417.75,"end":421.23,"name":"이성용","text":"계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.\n"},{"start":423.642,"end":429.346,"name":"AI","text":"알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n"}]

In [4]:
system_prompt = f'''
너는 회의 내용을 요약하는 봇이다. 아래 회의록을 읽고, 주요 내용을 요약하라.
결과는 마크다운 형식으로 작성한다.

아래 형식에 맞추어 작성하라.

# 회의 제목

## 주요 내용

## 참석자별 입장

## 결정 사항   

=============== 이하 회의록 ===============

{ meeting_note_txt }
'''

In [6]:
import google.genai as genai
from dotenv import load_dotenv
import os

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

In [7]:
# OpenAI API를 사용해 요약 결과 생성
response = client.models.generate_content(
    model=os.getenv("GEMINI_MODEL", "gemini-2.0-flash"),
    contents=system_prompt
)
summary = response.text

print(summary)

# 입문용 전기기타 선택에 대한 토론 (싼 기타 vs 비싼 기타)

## 주요 내용
전기기타를 처음 시작할 때 '저렴한 기타로 시작하는 것이 좋은가' 아니면 '비싼 기타로 시작하는 것이 좋은가'를 주제로 진행된 역할극 형식의 토론입니다. 양측은 경제성, 연습 효율성, 동기부여 등 다양한 관점에서 각자의 논리를 펼치며 유머러스하게 대화를 주고받았습니다.

## 참석자별 입장

### AI (싼 기타 시작 찬성)
* **부담 없는 연습:** 초보자는 실수나 관리에 미숙하여 기타에 흠집을 낼 수 있으므로, 심리적 부담이 적은 저렴한 모델로 시작하는 것이 좋음.
* **단계적 업그레이드:** 실력이 향상된 후에 본인의 취향을 파악하여 좋은 기타로 교체하는 것이 더 의미 있음.
* **리스크 관리:** 기타에 대한 흥미가 금방 떨어질 경우를 대비해 초기 투자 비용을 최소화해야 함.
* **품질 상향 평준화:** 최근 저가형 기타도 연습용으로는 충분히 좋은 품질을 갖추고 있음.

### 이성용 (비싼 기타 시작 찬성)
* **중복 투자 방지:** 어차피 나중에 좋은 기타를 사게 될 것이므로, 처음부터 비싼 모델을 구매해 이중 지출을 막아야 함.
* **객관적인 연습 태도:** 장비가 좋으면 실력이 부족할 때 '기타 탓'을 하지 않고 오로지 자신의 연습 부족을 반성하며 정진할 수 있음.
* **강력한 동기부여:** 큰 비용을 지불했다는 책임감과 기타에 대한 애착 덕분에 포기하지 않고 꾸준히 연습하게 됨.
* **연주 편의성:** 비싼 기타일수록 연주감이 편안하도록 제작되었기 때문에 초보자가 배우기에 훨씬 유리함.

## 결정 사항
* **정해진 정답 없음:** 각자의 경제적 상황과 성향(동기부여 방식 등)에 따라 선택이 달라질 수 있음을 확인했습니다.
* **본질의 중요성:** 어떤 기타를 선택하든 가장 중요한 것은 '꾸준한 연습'과 '악기에 대한 열정'이라는 점에 합의하며 즐거운 분위기 속에서 대화를 마무리했습니다.

In [9]:
with open('./audio/guitar_summary.md', 'w', encoding='utf-8') as f:
    f.write(summary)

In [10]:
df_meeting_note = df_rttm[['start', 'end', 'name', 'text']].copy()
df_meeting_note.dropna(inplace=True)

meeting_note_dict = df_meeting_note.to_dict(orient='records')  # 딕셔너리 형태로 변환
meeting_note_dict

[{'start': 0.976,
  'end': 30.195,
  'name': '이성용',
  'text': '지금부터 저랑 역할극을 합시다.\n역할극을 스탠드인 코미디 스타일로 할 건데\n토론을 하면서 자연스럽게 대화하는 형식으로 하면서\n코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요.\n자연스럽게.\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n어, 두 중에 어떤 역할 맡으실래요?\n'},
 {'start': 32.419,
  'end': 41.638000000000005,
  'name': 'AI',
  'text': '좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠? 네 맞아요. 준비 되셨나요?\n'},
 {'start': 42.674, 'end': 44.032, 'name': '이성용', 'text': '네, 됐어요. 시작하시죠.\n'},
 {'start': 45.798,
  'end': 67.105,
  'name': 'AI',
  'text': '좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.\n초보자일 때는 실수도 많고 기타에 익숙해지는 과정이 필요하니까\n비싼 기타보다는 부담�없이 연습할 수 있는 싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n'},
 {'start': 67.224,
  'end': 82.79299999999999,
  'name': '이성용',
  'text': '아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타 사고 쌍기타 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n'},
 {'start': 84.643,
  'end': 102.572,
  'name': 'AI',
  'text': '그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 쌍기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요.\n그리고 기타 연주에 익숙해지면 그때 비교할 수 있는 게 더 좋다고 생각해요.\n그리고 기타 현지에 익숙해지면\n그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데\n'},
 {'start': 103.489,
  'end': 117.53,
  'name': '이성용',
  'text': '싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데 기타를 싼 거 산다고 달라지나요?\n'},
 {'start': 119.737,
  'end': 138.667,
  'name': 'AI',
  'text': '하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에 부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요.\n그리고 싼 기타도 요즘은\n통질이 꽤 좋아서 연습용으로\n'},
 {'start': 139.346,
  'end': 168.956,
  'name': '이성용',
  'text': '충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타로 사서 하면 되는 거 아니에요?\n그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면\n자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.\n'},
 {'start': 170.925,
  'end': 192.318,
  'name': 'AI',
  'text': '하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기타를 기타의 흥미가 떨어지거나\n생각보다 연습시간이 적을 때\n아까울 수도 있습니다.\n이 기타의 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n'},
 {'start': 193.812,
  'end': 216.579,
  'name': '이성용',
  'text': '쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에요. 왜냐하면 그 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n측면에서도 비싼 기타가 훨씬 도움이 된다고\n생각을 합니다.\n'},
 {'start': 218.565,
  'end': 237.767,
  'name': 'AI',
  'text': '하하 비싼 기타가\n일종의 동기부여가 된다는\n말씀이시군요. 하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.\n그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n'},
 {'start': 238.175, 'end': 239.346, 'name': 'AI', 'text': '결국은 본인이 선택한...\n'},
 {'start': 241.044,
  'end': 251.316,
  'name': '이성용',
  'text': '근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n'},
 {'start': 253.659,
  'end': 271.553,
  'name': 'AI',
  'text': '맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게 선택하는 게 최선이겠네요.\n'},
 {'start': 272.148,
  'end': 304.541,
  'name': '이성용',
  'text': '아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와\n비싼 기타를 치더라도 이게 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로 비싼 기타를 치던 사람이\n싼 기타를 치면은\n아 이게 이렇게 싸구려구나 라는 걸\n금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 그 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작하는 게 좋죠.\n'},
 {'start': 306.986,
  'end': 326.035,
  'name': 'AI',
  'text': '하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히\n연습하는 게 제일 중요하겠죠?\n'},
 {'start': 326.358,
  'end': 335.459,
  'name': '이성용',
  'text': '맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n'},
 {'start': 337.547,
  'end': 355.934,
  'name': 'AI',
  'text': '그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n'},
 {'start': 356.256,
  'end': 363.981,
  'name': '이성용',
  'text': '아 맞아요.\n그 지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n'},
 {'start': 365.968,
  'end': 381.435,
  'name': 'AI',
  'text': '아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게 이야기 나누는 게 더 중요한 것 같아요\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n'},
 {'start': 382.165,
  'end': 383.727,
  'name': '이성용',
  'text': '어? 지금 도망가시는 건가요?\n'},
 {'start': 385.713,
  'end': 397.174,
  'name': 'AI',
  'text': '아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 혹시 화나셨나요?\n'},
 {'start': 401.435,
  'end': 406.596,
  'name': 'AI',
  'text': '아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n'},
 {'start': 407.326, 'end': 408.345, 'name': '이성용', 'text': '화난 것 같은데?\n'},
 {'start': 410.093,
  'end': 417.445,
  'name': 'AI',
  'text': '네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n'},
 {'start': 417.75,
  'end': 421.23,
  'name': '이성용',
  'text': '계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.\n'},
 {'start': 423.642,
  'end': 429.346,
  'name': 'AI',
  'text': '알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n'}]

In [14]:
for row in meeting_note_dict:    
    if not isinstance(row['text'], str): # 텍스트가 아닌 다른 형식인 경우 통과
        continue

    correction_system_prompt = f'''
        너는 주어진 회의 녹취록을 수정 및 보완하는 봇이다.
        주어진 회의 녹취록은 STT로 작성된 결과이므로, 이 중에 오류가 있는 부분을 찾아내고 수정하라.

        표현, 말투는 최대한 원본과 일치하도록 유지하되, 잘못 받아적은 내용을 수정하라.
        원본의 내용을 최대한 살리되, 잘못된 내용만 수정하라. 
        어떤 경우에는 A라는 사람이 말한 내용을 B가 말한 것으로 잘못 기록된 경우도 있을 수 있다. 이런 경우에는 문맥을 고려하여 수정하라.

        원본 내용 중 빠지거나, 추가되거나, 잘못 기록된 부분을 찾아내어 수정하라. 수정된 메시지 이외에는 아무것도 작성하지 말라.
        --------------------------------
        회의 요약문 : {summary}
        --------------------------------
        회의 녹취록 전문: {df_meeting_note.to_json(orient='records', force_ascii=False)}
        --------------------------------
        확인할 메시지 원본: {row['text']}
    '''

    response = client.models.generate_content(
        model=os.getenv("GEMINI_MODEL", "gemini-2.0-flash"),
        contents=correction_system_prompt
    )

    correction = response.text
    if ':' in correction:  # “수정: “ 과 같은 형식으로 반환되는 경우 해결 
        correction = correction.split(':')[-1]
        
    correction = correction.strip() # 좌우 공백 제거

    print(row['name'])
    print(row['text'])
    print(correction)
    print('-----------------')

    row['corrected_text'] = correction

이성용
지금부터 저랑 역할극을 합시다.
역할극을 스탠드인 코미디 스타일로 할 건데
토론을 하면서 자연스럽게 대화하는 형식으로 하면서
코미디를 진행해봅시다.
그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요.
자연스럽게.
그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐
아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐
이거를 입장을 나눠가지고
저랑 토론해보면 좋을 것 같아요.
어, 두 중에 어떤 역할 맡으실래요?

지금부터 저랑 역할극을 합시다.
역할극을 스탠드업 코미디 스타일로 할 건데
토론을 하면서 자연스럽게 대화하는 형식으로 하면서
코미디를 진행해봅시다.
그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요.
자연스럽게.
그리고 주제는 싼 기타로 전기기타를 시작하는 게 좋으냐
아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐
이거를 입장을 나눠가지고
저랑 토론해보면 좋을 것 같아요.
어, 둘 중에 어떤 역할 맡으실래요?
-----------------
AI
좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠? 네 맞아요. 준비 되셨나요?

좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성용님은 비싼 기타로 시작하는 게 좋다는 입장이시죠? 준비 되셨나요?
-----------------
이성용
네, 됐어요. 시작하시죠.

네, 준비됐습니다. 시작하시죠.
-----------------
AI
좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.
초보자일 때는 실수도 많고 기타에 익숙해지는 과정이 필요하니까
비싼 기타보다는 부담�없이 연습할 수 있는 싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?
성형님은 어떻게 생각하세요?

좋아요. 먼저 싼 기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.
초보자일 때는 실수도 많고 기타에 익숙해지는 과정이 필요하니까
비싼 기타보다는 부담 없이 연습할 수 있는 싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?
성용님은 어떻게 생각하세요?
-----------------
이성용
아, 저는 지금 말에 어폐가 있다고 생각해요.
왜냐하면 어차피 지금 비싼 기타로
나중에 살 생각을 하는 거잖아요.
그럼 어차피 비싼 기타 사고 쌍기타 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.

아, 저는 지금 말에 어폐가 있다고 생각해요. 왜냐하면 어차피 나중에 비싼 기타를 살 생각을 하는 거잖아요. 그럼 어차피 싼 기타 사고 비싼 기타 사게 되는데, 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면 이중 지출을 막을 수가 있습니다.
-----------------
AI
그런데 비싼 기타로 시작하면
혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?
초보 때는 실습을 많이 하니까 쌍기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요.
그리고 기타 연주에 익숙해지면 그때 비교할 수 있는 게 더 좋다고 생각해요.
그리고 기타 현지에 익숙해지면
그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데

그런데 비싼 기타로 시작하면 혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요? 초보 때는 실수를 많이 하니까 싼 기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요. 그리고 기타 연주에 익숙해지면 그때 비싼 기타를 사는 게 더 의미 있지 않을까요?
-----------------
이성용
싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데 기타를 싼 거 산다고 달라지나요?

아니 근데 어차피 비싼 기타를 살 건데 싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데 기타를 싼 거 산다고 달라지나요?
-----------------
AI
하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요.
비싼 기타를 사기 전에 부담없이 연습하면서
자신감을 키우는 것도 중요하다고 생각해요.
그리고 싼 기타도 요즘은
통질이 꽤 좋아서 연습용으로

하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요.
비싼 기타를 사기 전에 부담없이 연습하면서
자신감을 키우는 것도 중요하다고 생각해요.
그리고 싼 기타도 요즘은
품질이 꽤 좋아서 연습용으로 충분하죠.
-----------------
이성용
충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이
많이 좋아서
연습하는데 충분한 거는
맞는데
근데 뭐 돈이 있으면은 그냥 비싼 기타로 사서 하면 되는 거 아니에요?
그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면
자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.
근데 기타가 좋은 기타다.
그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.

충분하죠. 아 맞아요. 그것도 맞는 말이에요. 싼 기타도 요새 품질이 많이 좋아서 연습하는 데 충분한 거는 맞는데 근데 뭐 돈이 있으면은 그냥 비싼 기타로 사서 하면 되는 거 아니에요? 그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠. 근데 기타가 좋은 기타다. 그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.
-----------------
AI
하하
역시 좋은 기타를 사면 책임감도
더 커진다는 말씀이시군요. 그래도 비싼 기타를 기타의 흥미가 떨어지거나
생각보다 연습시간이 적을 때
아까울 수도 있습니다.
이 기타의 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.

하하, 역시 좋은 기타를 사면 책임감도 더 커진다는 말씀이시군요. 그래도 비싼 기타는 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요. 싼 기타로 시작해서 부담 없이 연습하고 정말 기타에 흥미가 생기면 그때 비싼 걸 사는 게 좋지 않나요?
-----------------
이성용
쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에요. 왜냐하면 그 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?
라는 생각이 들면서 계속
연습을 열심히 할 수가 있어요.
그래서 포기를 안 하게 되는
측면에서도 비싼 기타가 훨씬 도움이 된다고
생각을 합니다.

싼 기타로 시작해서 부담 없이 연습하고 정말 기타에 흥미가 생기면 그때 비싼 거 사는 게... 아니에요. 왜냐하면 그 싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 잃게 돼요. 그리고 비싼 기타를 사면 흥미를 잃게 되더라도 '어, 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?'라는 생각이 들면서 계속 연습을 열심히 할 수가 있어요. 그래서 포기를 안 하게 되는 측면에서도 비싼 기타가 훨씬 도움이 된다고 생각을 합니다.
-----------------
AI
하하 비싼 기타가
일종의 동기부여가 된다는
말씀이시군요. 하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?
특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.
그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.

하하, 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요. 하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요? 특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요. 그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.
-----------------
AI
결국은 본인이 선택한...

"결국은 본인이 싼 기타를..."}
-----------------
이성용
근데 그게 비싼 기타를 치면 더 편해요.
편하게 치는 게 중요하다고 하셨잖아요.
근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.

근데 그게 비싼 기타를 치면 더 편해요.
편하게 치는 게 중요하다고 하셨잖아요.
근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇겠어요?
-----------------
AI
맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.
하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.
그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.
결국 각자의 스타일과 상황에 맞게 선택하는 게 최선이겠네요.

맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.
하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.
그래서 싼 기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.
결국 각자의 스타일과 상황에 맞게 선택하는 게 최선이겠네요.
-----------------
이성용
아 그 말에 대해 동의를 합니다.
기타를 잘 못 치는 사람은
쌍기타와
비싼 기타를 치더라도 이게 비싼 기타를 치더라도 이게 왜 좋은 기타인지
이걸 잘 못 느끼긴 하죠.
근데 반대로 비싼 기타를 치던 사람이
싼 기타를 치면은
아 이게 이렇게 싸구려구나 라는 걸
금방 느낄 수가 있습니다
그래서 처음부터 비싼 기타를 쳐서
그런 그 쌍기타의 맛을 모르고 살아도 되는데
왜 그 맛없는 맛을
굳이 초반부터 느끼려고 합니까?
그러니까 비싼 기타로 시작하는 게 좋죠.

아 그 말에 대해 동의를 합니다.
기타를 잘 못 치는 사람은
싼 기타와
비싼 기타를 치더라도 이게 왜 좋은 기타인지
이걸 잘 못 느끼긴 하죠.
근데 반대로 비싼 기타를 치던 사람이
싼 기타를 치면은
아 이게 이렇게 싸구려구나 라는 걸
금방 느낄 수가 있습니다.
그래서 처음부터 비싼 기타를 쳐서
그런 그 싼 기타의 맛을 모르고 살아도 되는데
왜 그 맛없는 맛을
굳이 초반부터 느끼려고 합니까?
그러니까 비싼 기타로 시작하는 게 좋죠.
-----------------
AI
하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.
하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니
처음엔 가볍게 접근하는 게 더 좋다고 봅니다.
어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히
연습하는 게 제일 중요하겠죠?

하하! 싼 기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.
하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니
처음엔 가볍게 접근하는 게 더 좋다고 봅니다.
어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히
연습하는 게 제일 중요하겠죠?
-----------------
이성용
맞아요. 그래서 비싼 기타를 사야 되는 거예요.
비싼 기타를 사면 꾸준히 연습을 하게 됩니다.
왜냐하면 계속 그 기타를 만지고 있고 싶거든요.
왜냐면 감촉도 훨씬 좋고 그러니까요.

맞아요. 그래서 비싼 기타를 사야 되는 거예요.
비싼 기타를 사면 꾸준히 연습을 하게 됩니다.
왜냐하면 계속 그 기타를 만지고 싶어지거든요.
연주감도 훨씬 좋고 그러니까요.
-----------------
AI
그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.
하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.
결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.
소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.

그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.
하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.
결국 어떤 기타를 선택하든 가장 중요한 건 그 연습과 열정일 것 같아요.
소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.
-----------------
이성용
아 맞아요.
그 지금 얘기하신 거 보니까
쌍기타가 더 좋다는 얘기는 안 하시네요.

아 맞아요.
그 지금 얘기하신 거 보니까
싼 기타가 더 좋다는 얘기는 안 하시네요.
-----------------
AI
아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는
재밌게 이야기 나누는 게 더 중요한 것 같아요
가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.
결국 중요한 건 기타를 사랑하는 마음이겠죠.
앞으로도 즐겁게 연습하시길 바래요.

아무래도 성용님이 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는
재밌게 이야기 나누는 게 더 중요한 것 같아요.
각자 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.
결국 중요한 건 기타를 사랑하는 마음이겠죠.
앞으로도 즐겁게 연습하시길 바래요.
-----------------
이성용
어? 지금 도망가시는 건가요?

"알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n"}]
-----------------
AI
아니요. 전혀 그렇지 않아요.
전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.
토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.
혹시 더 이야기하고 싶으신 게 있나요? 혹시 화나셨나요?

아니요. 전혀 그렇지 않아요.
전 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.
토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.
혹시 더 이야기하고 싶으신 게 있나요?
-----------------
AI
아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.

아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정 마세요.
-----------------
이성용
화난 것 같은데?

"알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n"}]
-----------------
AI
네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.

네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요. 계속해서 이야기 나누고 싶으시면 편하게 말씀해 주세요.
-----------------
이성용
계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.

아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 이쯤 하시죠.
-----------------
AI
알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.

알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.
-----------------

In [15]:
# meeting_note_dict json 파일로 저장
import json

with open('./audio/guitar_meeting_note_corrected.json', 'w', encoding='utf-8') as f:
    json.dump(meeting_note_dict, f, ensure_ascii=False, indent=4)

In [16]:
md_template = ""

for row in meeting_note_dict:
    md_template += f"- **{row['name']}** : {row['corrected_text']}\n"

with open('./audio/guitar_meeting_note_corrected.md', 'w', encoding='utf-8') as f:
    f.write(md_template)

In [17]:
%pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting lxml>=3.1.0 (from python-docx)
  Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl.metadata (3.7 kB)
Requirement already satisfied: typing_extensions>=4.9.0 in .\venv312\lib\site-packages (from python-docx) (4.15.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 4.0/4.0 MB 34.4 MB/s eta 0:00:00
Installing collected packages: lxml, python-docx
Successfully installed lxml-6.0.2 python-docx-1.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
from docx import Document

document = Document()   # (1)  docx 객체 생성
document.add_heading('회의록', level=1) # (2) 제목 추가

table = document.add_table(rows=1, cols=2) # (3) 테이블 생성
table.style = 'Table Grid' # (4) 테이블 스타일 지정

hdr_cells = table.rows[0].cells # (5) 첫 번째 행에 셀 추가
hdr_cells[0].text = 'Speaker' # (6) 첫 번째 셀에 Speaker 추가
hdr_cells[1].text = 'Content'   # (7) 두 번째 셀에 Content 추가

# (8) 수정된 녹취록 파일을 읽어들여서 테이블에 추가
for row in meeting_note_dict:
    row_cells = table.add_row().cells
    row_cells[0].text = row['name']
    row_cells[1].text = row['corrected_text']


document.save('./audio/guitar_meeting_note_corrected.docx') # (9) docx 파일 저장